### ISSUE TITLE
AttributeError: module 'homeassistant.helpers.config_validation' has no attribute 'config_entry_only_config_schema'

### ISSUE THREAD

**Issue by iwangzhuo** [mudape/iphonedetect#125]
此错误来自自定义集成。

Logger: homeassistant.loader
Source: custom_components/iphonedetect/__init__.py:19
Integration: iPhone Device Tracker (documentation, issues)
First occurred: 16:12:40 (1 occurrences)
Last logged: 16:12:40

Unexpected exception importing component custom_components.iphonedetect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/iphonedetect/__init__.py", line 19, in <module>
    CONFIG_SCHEMA = cv.config_entry_only_config_schema(DOMAIN)
AttributeError: module 'homeassistant.helpers.config_validation' has no attribute 'config_entry_only_config_schema'

**Comment by mudape** [comment]
Hi @iwangzhuo 
I can't reproduce this, is it still an issue?
