### ISSUE TITLE
OSError: [Errno 47] Address family not supported by protocol family

### ISSUE THREAD

**Issue by elyobelyob** [mudape/iphonedetect#73]
Getting this message on my recently upgraded install.

I'm running on a TrueNAS installation, so not sure if this could be part of the issue.

`Error setting up entry My iPhone for iphonedetect
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/homeassistant/custom_components/iphonedetect/__init__.py", line 75, in async_setup_entry
    _mac = await IphoneDetectScanner.get_mac_address(entry.data[CONF_IP_ADDRESS])
  File "/home/homeassistant/homeassistant/custom_components/iphonedetect/scanner.py", line 45, in get_mac_address
    probe = list(IPRoute().get_neighbours(dst=ip)[0]["attrs"])
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/pr2modules/iproute/linux.py", line 140, in __init__
    super(RTNL_API, self).__init__(*argv, **kwarg)
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/pr2modules/netlink/rtnl/iprsocket.py", line 31, in __init__
    super(IPRSocketMixin, self).__init__(NETLINK_ROUTE, *argv[1:], **kwarg)
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/pr2modules/netlink/nlsocket.py", line 415, in __init__
    self.post_init()
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/pr2modules/netlink/nlsocket.py", line 1018, in post_init
    self._sock = config.SocketBase(
  File "/usr/local/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 47] Address family not supported by protocol family`

**Comment by mudape** [comment]
Hi @elyobelyob 

I'm not familiar with TrueNAS.
Are you running HASS in an container/vm or what OS is used?
Maybe some permission needs adjusting?

PyRoute2 needs [linux](https://github.com/svinota/pyroute2/issues/437) with netlink.

**Comment by elyobelyob** [comment]
I think I already know the answer. @tprelog will confirm ...

**Comment by tprelog** [comment]
Home Assistant on TrueNAS Core is virtual environment install on FreeBSD based OS

> PyRoute2 needs Linux with netlink.

Sorry @elyobelyob - FreeBSD is not going to be compatible with this.

**Comment by elyobelyob** [comment]
Yup, I knew you'd know, pretty sure we hit this blocker previously.
