### ISSUE TITLE
Python Errors When Upgrading to HA 2022.6.3

### ISSUE THREAD

**Issue by wastingaeons** [mudape/iphonedetect#77]
Upgrading to HA 2022.6.3 using the LinuxServer container seems to break iphonedetect. Downgrading to 2022.6.2 works as expected. It doesn't look like any breaking changes were made to the container, but I am not sure.

Python trace:
```Logger: homeassistant.loader
Source: .local/lib/python3.9/site-packages/pyroute2/__init__.py:79
First occurred: 2:15:50 PM (2 occurrences)
Last logged: 2:15:52 PM

Unexpected exception importing component custom_components.iphonedetect
Unexpected exception importing platform custom_components.iphonedetect.device_tracker
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/iphonedetect/__init__.py", line 29, in <module>
    from .scanner import IphoneDetectScanner
  File "/config/custom_components/iphonedetect/scanner.py", line 4, in <module>
    from pyroute2 import IPRoute
  File "/config/.local/lib/python3.9/site-packages/pyroute2/__init__.py", line 79, in <module>
    loaded = entry_point.load()
  File "/usr/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 205, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'pr2modules.iproute' has no attribute 'ChaoticIPRoute'```

**Comment by mudape** [comment]
Hi @wastingaeons 
Strange!
I switched to `image: ghcr.io/home-assistant/home-assistant:2022.6.3` but don't see what you are seeing.

## System Health

version | core-2022.6.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.12
os_name | Linux
os_version | 4.19.0-19-amd64
arch | x86_64


Was pyroute2 succesfully installed in your container?

```
/config # pip list|grep pyroute
pyroute2                         0.6.9
pyroute2.core                    0.6.9
pyroute2.ethtool                 0.6.9
pyroute2.ipdb                    0.6.9
pyroute2.ipset                   0.6.9
pyroute2.ndb                     0.6.9
pyroute2.nftables                0.6.9
pyroute2.nslink                  0.6.9
```

**Comment by wastingaeons** [comment]
Interesting. pyroute2 looks good, so I suppose its something else with LinuxServer's container.  Only thing different in system health between yours, is its using python 3.9.5

Spose I can/should use the official container anyway. Thanks!
