### ISSUE TITLE
No module named 'pr2modules.ethtool'

### ISSUE THREAD

**Issue by OToussaint** [mudape/iphonedetect#79]
Hello, 

It is me again, with another problem this time.
The integration refuse to load in HA 2022.7.0

```
Jul 07 12:49:02 hassbian hass[12876]: 2022-07-07 12:49:02 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration iphonedetect: Unable to import component: No module named 'pr2modules.ethtool'
Jul 07 12:49:03 hassbian hass[12876]: 2022-07-07 12:49:03 ERROR (MainThread) [homeassistant.config] Platform error: device_tracker
Jul 07 12:49:03 hassbian hass[12876]: Traceback (most recent call last):
Jul 07 12:49:03 hassbian hass[12876]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config.py", line 877, in async_process_component_config
Jul 07 12:49:03 hassbian hass[12876]:     platform = p_integration.get_platform(domain)
Jul 07 12:49:03 hassbian hass[12876]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 618, in get_platform
Jul 07 12:49:03 hassbian hass[12876]:     cache[full_name] = self._import_platform(platform_name)
Jul 07 12:49:03 hassbian hass[12876]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 635, in _import_platform
Jul 07 12:49:03 hassbian hass[12876]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
Jul 07 12:49:03 hassbian hass[12876]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Jul 07 12:49:03 hassbian hass[12876]:     return _bootstrap._gcd_import(name[level:], package, level)
Jul 07 12:49:03 hassbian hass[12876]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Jul 07 12:49:03 hassbian hass[12876]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Jul 07 12:49:03 hassbian hass[12876]:   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
Jul 07 12:49:03 hassbian hass[12876]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Jul 07 12:49:03 hassbian hass[12876]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Jul 07 12:49:03 hassbian hass[12876]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Jul 07 12:49:03 hassbian hass[12876]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Jul 07 12:49:03 hassbian hass[12876]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Jul 07 12:49:03 hassbian hass[12876]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
Jul 07 12:49:03 hassbian hass[12876]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Jul 07 12:49:03 hassbian hass[12876]:   File "/home/homeassistant/.homeassistant/custom_components/iphonedetect/__init__.py", line 29, in <module>
Jul 07 12:49:03 hassbian hass[12876]:     from .scanner import IphoneDetectScanner
Jul 07 12:49:03 hassbian hass[12876]:   File "/home/homeassistant/.homeassistant/custom_components/iphonedetect/scanner.py", line 4, in <module>
Jul 07 12:49:03 hassbian hass[12876]:     from pyroute2 import IPRoute
Jul 07 12:49:03 hassbian hass[12876]:   File "/srv/homeassistant/lib/python3.9/site-packages/pyroute2/__init__.py", line 79, in <module>
Jul 07 12:49:03 hassbian hass[12876]:     loaded = entry_point.load()
Jul 07 12:49:03 hassbian hass[12876]:   File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
Jul 07 12:49:03 hassbian hass[12876]:     module = import_module(match.group('module'))
Jul 07 12:49:03 hassbian hass[12876]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Jul 07 12:49:03 hassbian hass[12876]:     return _bootstrap._gcd_import(name[level:], package, level)
Jul 07 12:49:03 hassbian hass[12876]: ModuleNotFoundError: No module named 'pr2modules.ethtool'

```

I've checked, pyroute2.ethtool is installed, as you can see bellow:

```
pyroute2                   0.6.9
pyroute2.core              0.6.9
pyroute2.ethtool           0.6.9
pyroute2.ipdb              0.6.9
pyroute2.ipset             0.6.9
pyroute2.ndb               0.6.9
pyroute2.nftables          0.6.9
pyroute2.nslink            0.6.9

```

But I can't remember if this was upgrade by the upgrade to 2022.7.0 (maybe)
Btw, this release is supposed to be Python 3.10 compliant, which might be the cause.
And, finally,

## System Health

version | core-2022.7.0
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | homeassistant
virtualenv | true
python_version | 3.9.2
os_name | Linux
os_version | 5.15.32-v7+
arch | armv7l
timezone | Europe/Brussels
config_dir | /home/homeassistant/.homeassistant

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4016
Installed Version | 1.25.5
Stage | running
Available Repositories | 1143
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 17
views | 26
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 9 juin 2022 à 20:32
-- | --
current_recorder_run | 7 juillet 2022 à 12:48
estimated_db_size | 1851.19 MiB
database_engine | mysql
database_version | 10.3.32

</details>

<details><summary>Sonoff</summary>

version | 3.1.0 (3871c0b)
-- | --
cloud_online | 1 / 1
local_online | 1 / 1

</details>

**Comment by mudape** [comment]
Hi again @OToussaint 
Thanks for reporting!
Your virtual env is running Python3.9, do other stuff work?

I haven't upgraded to 2022.7 yet.. Busy with life and work

**Comment by OToussaint** [comment]
Yes, indeed, you're right, my venv is running Python 3.9 although I'm not really sure after I did a few commands:

```
(homeassistant) homeassistant@hassbian:/srv/homeassistant $ python3 --version
Python 3.9.2
(homeassistant) homeassistant@hassbian:/srv/homeassistant $ python --version
Python 3.8.6
(homeassistant) homeassistant@hassbian:/srv/homeassistant $ python2 --version
Python 2.7.18

```

Every other integrations (officals or hacs) are running fine. Just yours is complaining.
No hurry, in the meantime I've setup a ping sensor, life and work before this.
I'll try to remove this 3.8.6 that is bugging me. I'll let you know if this solves my issue.

**Comment by OToussaint** [comment]
Ok, I was going insane

```
(homeassistant) homeassistant@hassbian:/srv/homeassistant $ python --version
Python 3.8.6
(homeassistant) homeassistant@hassbian:/srv/homeassistant $ which python
/srv/homeassistant/bin/python
(homeassistant) homeassistant@hassbian:/srv/homeassistant $ /srv/homeassistant/bin/python --version
Python 3.9.2
```

Whaaaaaaat ?
I did a massive find after every python* and remove the one replying 3.8.6, problem solved.
My bad, sorry to have disturbed you.
