### ISSUE TITLE
Config entry was never loaded

### ISSUE THREAD

**Issue by weaseel** [mudape/iphonedetect#97]
I get an error while starting/reloading the addon:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 543, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 80, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 194, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

It worked fine in the past. Currently running the latest version 2.0.5
Home assistant 2023.6.2
OS 10.3

**Comment by weaseel** [comment]
Reinstall in hacs fixed it
